service: markab-backend 
org: itechdom
provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev
  environment:
    NODE_ENV: dev
    DB_URI: ${ssm:/kflow/DB_URI} # Use SSM Parameter Store for sensitive data
    SERVER_PORT: 3000
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "secretsmanager:GetSecretValue"
      Resource: 
        - "arn:aws:secretsmanager:${self:provider.region}:${aws:accountId}:secret:/kflow/DB_URI*"
functions:
  app:
    handler: index.handler
    events:
      - http: 
          path: /{proxy+}
          method: any
plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin
custom:
  bundle:
    linting: false
    externals: all
  serverless-offline:
    port: 3000
resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ExpressApi
package:
  exclude:
    - node_modules/**
    - .git/**
    - docs/**
    - scripts/**
    - tests/**
    - coverage/**
    - Libs/**
    - media/**
    - docs/**