service: express-app

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  stage: dev
  environment:
    NODE_ENV: dev
    DB_URI: ${ssm:/kflow/DB_URI} # Use SSM Parameter Store for sensitive data
    SERVER_PORT: 3000
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "secretsmanager:GetSecretValue"
      Resource: "arn:aws:secretsmanager:${self:provider.region}:*:secret:/kflow/DB_URI"

functions:
  app:
    handler: handler.handler
    events:
      - http: 
          path: /{proxy+}
          method: any

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    port: 3000

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ExpressApi

package:
  exclude:
    - node_modules/**
    - .git/**
    - docs/**
    - scripts/**
    - tests/**
    - coverage/**